CREATE TABLE  doctors (
  UID int(10) unsigned NOT NULL AUTO_INCREMENT,
  EMAIL varchar(45) NOT NULL DEFAULT '',
  UPASS varchar(65) NOT NULL DEFAULT '',
  AUTH_KEY varchar(512) NOT NULL,
  USED_KEY JSON NOT NULL DEFAULT '[]',
  PRIMARY KEY (UID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;